--- # Greetings
name: Greetings

on: [pull_request, issues]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' || !startsWith(github.head_ref, 'dependabot/') }}
    steps:
      - uses: actions/first-interaction@v3.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: "Your first issue!"
          pr_message: "Your first Pull Request!"
